---
# tasks file for vm-netgear
- name: Installing packages specific to supporting netgear functionality
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - python-firewall
- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  become: yes
- name: Set external as default policy
  command: firewall-cmd --set-default-zone=internal
  become: yes
- name: Add internal firewall services
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes zone=internal
  become: yes
  with_items:
    - dns
    - dhcp
    - ssh
- name: Add external firewall services
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes zone=external
  become: yes
  with_items:
    - ssh
- name: Remove default firewall services from work
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=work
  become: yes
  with_items:
    - dhcpv6-client
    - ssh
- name: Remove default firewall services from internal
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=work
  become: yes
  with_items:
    - samba-client
- name: Remove default firewall services from home
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=home
  become: yes
  with_items:
    - dhcpv6-client
    - mdns
    - samba-client
    - ssh
- name: Remove default firewall services from dmz
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=dmz
  become: yes
  with_items:
    - ssh
- name: Remove default firewall services from public
  firewalld: service={{ item }} state=disabled permanent=yes immediate=yes zone=public
  become: yes
  with_items:
    - dhcpv6-client
    - ssh
#- name: Update firewall for routing
#  command: firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o enp0s3 -j MASQUERADE
#  become: yes
#- name: Update firewall for routing
#  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i enp0s3 -o enp0s8 -m state --state REALATED,ESTABLISHED -j ACCEPT
#  become: yes
#- name: Update firewall for routing
#  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i enp0s8 -o enp0s3 -j ACCEPT
#  become: yes
- name: Enable routing between interfaces
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv4.ip_forward = 1
  become: yes
