---
# tasks file for vm-netgear
- name: Change host to using static address
  copy:
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s8
    src: ifcfg-enp0s8
  become: yes
- name: Installing packages specific to supporting netgear functionality
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - dnsmasq
    - python-firewall
- name: Create /etc/dnsmasq.conf from template
  template:
    src: dnsmasq.conf.js
    dest: /etc/dnsmasq.conf
    backup: yes
  become: yes
- name: Set lower bound of dynamic IP address pool
  replace:
    dest: /etc/dnsmasq.conf
    regexp: '0-MIN'
    replace: '2'
  become: yes
- name: Set upper bound of dynamic IP address pool
  replace:
    dest: /etc/dnsmasq.conf
    regexp: '0-MAX'
    replace: '2'
  become: yes
- name: Enable services at boot
  service: name={{ item }} enabled=yes state=started
  become: yes
  with_items:
    - dnsmasq
    - firewalld
- name: Update firewall services
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes
  become: yes
  with_items:
    - dns
    - dhcp
- name: Update firewall for routing
  command: firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o enp0s3 -j MASQUERADE
  become: yes
- name: Update firewall for routing
  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i enp0s3 -o enp0s8 -m state --state REALATED,ESTABLISHED -j ACCEPT
  become: yes
- name: Update firewall for routing
  command: firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i enp0s8 -o enp0s3 -j ACCEPT
  become: yes
- name: Enable routing between interfaces
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv4.ip_forward = 1
  become: yes
